### ISSUE TITLE
Internal errors in YunoHost while installing LimeSurvey yunohost/issues#1084 

### ISSUE THREAD

**Issue by Psycojoker** [YunoHost-Apps/limesurvey_ynh#39]
Hello,

This is a copy/pasta from https://github.com/YunoHost/issues/issues/1084

###### Original Redmine Issue: [1085](https://dev.yunohost.org/issues/1085)

Author Name: **win8linux**

---

YunoHost encounters internal errors during installation of LimeSurvey. Below are the details from the webinterface.

Action

~~~ text
POST /apps


{"locale":"en","app":"limesurvey","args":"domain=garate.nohost.me&path=%2Fpoll&admin=sysadmin&language=en_GB","label":"LimeSurvey"}
~~~

Traceback

~~~ text
Traceback (most recent call last):
  File "/usr/lib/python2.7/dist-packages/moulinette/interfaces/api.py", line 406, in process
    ret = self.actionsmap.process(arguments, timeout=30, route=_route)
  File "/usr/lib/python2.7/dist-packages/moulinette/actionsmap.py", line 495, in process
    return func(**arguments)
  File "/usr/lib/moulinette/yunohost/app.py", line 692, in app_install
    _check_manifest_requirements(manifest, app_id)
  File "/usr/lib/moulinette/yunohost/app.py", line 1735, in _check_manifest_requirements
    m18n.g('colon', m18n.n('app_incompatible'), app=app_instance_name),
  File "/usr/lib/python2.7/dist-packages/moulinette/core.py", line 205, in n
    return self._namespaces[self._current_namespace].translate(key, *args, **kwargs)
  File "/usr/lib/python2.7/dist-packages/moulinette/core.py", line 92, in translate
    return self._translations[self.locale][key].encode('utf-8').format(*args, **kwargs)
KeyError: 'app'
~~~

**Comment by lleeooss** [comment]
Hello, installation of LimeSurvey in Yunohost with result "The operation 'Install 'limesurvey' application' has failed!" with log:
2019-10-06 16:50:26,668: DEBUG - Načítají se seznamy balíků…
2019-10-06 16:50:27,070: DEBUG - Vytváří se strom závislostí…
2019-10-06 16:50:27,070: DEBUG - Načítají se stavové informace…
2019-10-06 16:50:27,472: DEBUG - Opravují se závislosti… Hotovo
2019-10-06 16:50:28,073: DEBUG - Následující balíky budou ODSTRANĚNY:
2019-10-06 16:50:28,074: DEBUG -   limesurvey-ynh-deps
2019-10-06 16:50:28,175: DEBUG - 0 aktualizováno, 0 nově instalováno, 1 k odstranění a 0 neaktualizováno.
2019-10-06 16:50:28,175: WARNING - E: Balík je potřeba odstranit ale funkce Odstranit je vypnuta.
2019-10-06 16:50:28,176: DEBUG - + ynh_die '--message=Unable to install dependencies'
2019-10-06 16:50:28,177: WARNING - Unable to install dependencies
2019-10-06 16:50:28,178: DEBUG - + local legacy_args=mc
2019-10-06 16:50:28,178: DEBUG - + args_array=([m]=message= [c]=ret_code=)
2019-10-06 16:50:28,179: DEBUG - + declare -Ar args_array
2019-10-06 16:50:28,179: DEBUG - + local message
2019-10-06 16:50:28,179: DEBUG - + local ret_code
2019-10-06 16:50:28,180: DEBUG - + ynh_handle_getopts_args '--message=Unable to install dependencies'
2019-10-06 16:50:28,180: DEBUG - + set +x
2019-10-06 16:50:28,181: DEBUG - + echo 'Unable to install dependencies'
2019-10-06 16:50:28,181: DEBUG - + exit 1
2019-10-06 16:50:28,181: DEBUG - + ynh_exit_properly
2019-10-06 16:50:28,182: DEBUG - + local exit_code=1
2019-10-06 16:50:28,182: DEBUG - + '[' 1 -eq 0 ']'
2019-10-06 16:50:28,183: DEBUG - + trap '' EXIT
2019-10-06 16:50:28,183: DEBUG - + set +eu
2019-10-06 16:50:28,183: DEBUG - + sleep 0.5
2019-10-06 16:50:28,686: DEBUG - + ynh_print_err '--message=!!\n  limesurvey'\''s script has encountered an error. Its execution was cancelled.\n!!'
2019-10-06 16:50:28,687: WARNING - [91m[1m[ERR][0m !!
2019-10-06 16:50:28,689: DEBUG - + local legacy_args=m
2019-10-06 16:50:28,690: WARNING -   limesurvey's script has encountered an error. Its execution was cancelled.
2019-10-06 16:50:28,692: DEBUG - + args_array=([m]=message=)
2019-10-06 16:50:28,693: WARNING - !!
2019-10-06 16:50:28,695: DEBUG - + declare -Ar args_array
2019-10-06 16:50:28,696: WARNING - 
2019-10-06 16:50:28,698: DEBUG - + local message
2019-10-06 16:50:28,699: DEBUG - + ynh_handle_getopts_args '--message=!!\n  limesurvey'\''s script has encountered an error. Its execution was cancelled.\n!!'
2019-10-06 16:50:28,700: DEBUG - + set +x
2019-10-06 16:50:28,701: DEBUG - + ynh_print_log '\e[91m\e[1m[ERR]\e[0m !!\n  limesurvey'\''s script has encountered an error. Its execution was cancelled.\n!!'
2019-10-06 16:50:28,701: DEBUG - + echo -e '\e[91m\e[1m[ERR]\e[0m !!\n  limesurvey'\''s script has encountered an error. Its execution was cancelled.\n!!'
2019-10-06 16:50:28,702: DEBUG - + '[' api == cli ']'
2019-10-06 16:50:28,703: DEBUG - + type -t ynh_clean_setup
2019-10-06 16:50:28,704: DEBUG - + ynh_die
2019-10-06 16:50:28,705: DEBUG - + local legacy_args=mc
2019-10-06 16:50:28,706: DEBUG - + args_array=([m]=message= [c]=ret_code=)
2019-10-06 16:50:28,707: DEBUG - + declare -Ar args_array
2019-10-06 16:50:28,708: DEBUG - + local message
2019-10-06 16:50:28,708: DEBUG - + local ret_code
2019-10-06 16:50:28,709: DEBUG - + ynh_handle_getopts_args
2019-10-06 16:50:28,710: DEBUG - + set +x
2019-10-06 16:50:28,711: DEBUG - + echo ''
2019-10-06 16:50:28,712: DEBUG - + exit 1

**Comment by alexAubin** [comment]
Closing because the original issue is like 1.5 year old and that apparently was a story of "yunohost was not up to date enough to be able to install this app" (c.f. call to _check_manifest_requirements ... ) but at that point the code handling that exception was broken...
